apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-node
  labels:
    k8s-app: "aws-node"
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      k8s-app: "aws-node"
  template:
    metadata:
      labels:
        k8s-app: "aws-node"
    spec:
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 10
      priorityClassName: system-node-critical
      hostNetwork: true
      initContainers:
      - name: aws-vpc-cni-init
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.9.3
        env:
        - name: "DISABLE_TCP_EARLY_DEMUX"
          value: "false"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
      containers:
      - name: aws-node
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.9.3
        securityContext:
          capabilities:
            add:
            - "NET_ADMIN"
        resources:
          requests:
            cpu: 10m
        env:
        - name: "ADDITIONAL_ENI_TAGS"
          value: "{}"
        - name: "AWS_VPC_CNI_NODE_PORT_SUPPORT"
          value: "true"
        - name: "AWS_VPC_ENI_MTU"
          value: "9001"
        - name: "AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER"
          value: "false"
        - name: "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG"
          value: "false"
        - name: "AWS_VPC_K8S_CNI_EXTERNALSNAT"
          value: "false"
        - name: "AWS_VPC_K8S_CNI_LOGLEVEL"
          value: "DEBUG"
        - name: "AWS_VPC_K8S_CNI_LOG_FILE"
          value: "/host/var/log/aws-routed-eni/ipamd.log"
        - name: "AWS_VPC_K8S_CNI_RANDOMIZESNAT"
          value: "prng"
        - name: "AWS_VPC_K8S_CNI_VETHPREFIX"
          value: "eni"
        - name: "AWS_VPC_K8S_PLUGIN_LOG_FILE"
          value: "/var/log/aws-routed-eni/plugin.log"
        - name: "AWS_VPC_K8S_PLUGIN_LOG_LEVEL"
          value: "DEBUG"
        - name: "DISABLE_INTROSPECTION"
          value: "false"
        - name: "DISABLE_METRICS"
          value: "false"
        - name: "DISABLE_NETWORK_RESOURCE_PROVISIONING"
          value: "false"
        - name: "ENABLE_POD_ENI"
          value: "false"
        - name: "ENABLE_PREFIX_DELEGATION"
          value: "false"
        - name: "MY_NODE_NAME"
          valueFrom:
            fieldRef:
              fieldPath: "spec.nodeName"
        - name: "WARM_ENI_TARGET"
          value: "1"
        - name: "WARM_PREFIX_TARGET"
          value: "1"
        ports:
        - name: metrics
          containerPort: 61678
        livenessProbe:
          exec:
            command:
            - "/app/grpc-health-probe"
            - "-addr=:50051"
          initialDelaySeconds: 60
        readinessProbe:
          exec:
            command:
            - "/app/grpc-health-probe"
            - "-addr=:50051"
          initialDelaySeconds: 1
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cni-bin-dir
        - mountPath: /host/etc/cni/net.d
          name: cni-net-dir
        - mountPath: /host/var/log/aws-routed-eni
          name: log-dir
        - mountPath: /var/run/aws-node
          name: run-dir
        - mountPath: /var/run/dockershim.sock
          name: dockershim
        - mountPath: /run/xtables.lock
          name: xtables-lock
      volumes:
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: dockershim
        hostPath:
          path: /var/run/dockershim.sock
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
      - name: log-dir
        hostPath:
          path: /var/log/aws-routed-eni
          type: DirectoryOrCreate
      - name: run-dir
        hostPath:
          path: /var/run/aws-node
          type: DirectoryOrCreate
      tolerations:
      - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "beta.kubernetes.io/os"
                operator: In
                values:
                - "linux"
              - key: "beta.kubernetes.io/arch"
                operator: In
                values:
                - "amd64"
                - "arm64"
              - key: "eks.amazonaws.com/compute-type"
                operator: NotIn
                values:
                - "fargate"
            - matchExpressions:
              - key: "kubernetes.io/os"
                operator: In
                values:
                - "linux"
              - key: "kubernetes.io/arch"
                operator: In
                values:
                - "amd64"
                - "arm64"
              - key: "eks.amazonaws.com/compute-type"
                operator: NotIn
                values:
                - "fargate"
