apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: kube-system
commonLabels:
  app.kubernetes.io/part-of: "kube-state-metrics"

images:
- name: "k8s.gcr.io/kube-state-metrics/kube-state-metrics"
  newTag: "v2.1.0"
