apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: traefic
labels:
- pairs:
    app.kubernetes.io/version: "v2.9.1"
  includeSelectors: false

images:
- name: "traefik"
  newTag: "2.9.1"
