apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- rbac.yaml

namespace: kube-system
commonLabels:
  app.kubernetes.io/version: "v0.4.4"

images:
- name: "ghcr.io/external-secrets/external-secrets"
  newTag: "v0.4.4"
