apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-monitor.argocd-metrics.yaml
- service-monitor.argocd-server-metrics.yaml
- service-monitor.argocd-repo-server-metrics.yaml
- service-monitor.argocd-applicationset-controller-metrics.yaml

namespace: default
