apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-server-extensions-role.yaml
- argocd-server-extensions-rolebinding.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: "argocd-extensions"
    app.kubernetes.io/version: "v0.2.1"
  includeTemplates: true
