# Domains
"addons":
- changed-files:
  - any-glob-to-any-file:
    - addons/**/*

"misc":
- changed-files:
  - any-glob-to-any-file:
    - misc/**/*

"observability":
- changed-files:
  - any-glob-to-any-file:
    - observability/**/*
