apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:batch:view
  labels:
    rbac.authorization.k8s.io/unit: "batch-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
