apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:customresourcedefinitions:admin
  labels:
    rbac.authorization.k8s.io/unit: "customresourcedefinitions-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
## Cluster Scoped
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions/status
  verbs:
  - get
  - patch
  - update
