apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:customresourcedefinitions:view
  labels:
    rbac.authorization.k8s.io/unit: "customresourcedefinitions-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
## Cluster Scoped
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
