apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:daemonsets:view
  labels:
    rbac.authorization.k8s.io/unit: "daemonsets-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
