apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:deployments:admin
  labels:
    rbac.authorization.k8s.io/unit: "deployments-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - deployments/status
  - replicasets/scale
  - replicasets/status
  verbs:
  - get
  - patch
  - update
