apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:ingresses:admin
  labels:
    rbac.authorization.k8s.io/unit: "ingresses-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
