apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:namespaces:admin
  labels:
    rbac.authorization.k8s.io/unit: "namespaces-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
## Cluster Scoped
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/finalize
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
## Namspace Scoped
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas/status
  verbs:
  - get
  - patch
  - update
