apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:nodes:view
  labels:
    rbac.authorization.k8s.io/unit: "nodes-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
## Cluster Scoped
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
