apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:pods:log
  labels:
    rbac.authorization.k8s.io/unit: "pods-log"
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
