apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:pods:shell
  labels:
    rbac.authorization.k8s.io/unit: "pods-shell"
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
