apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:pods:portforward
  labels:
    rbac.authorization.k8s.io/unit: "pods-portforward"
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - get
