apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:rbac:view
  labels:
    rbac.authorization.k8s.io/unit: "rbac-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
## Cluster Scoped
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
## Namspace Scoped
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
