apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:serviceaccounts:view
  labels:
    rbac.authorization.k8s.io/unit: "serviceaccounts-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
