apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:services:admin
  labels:
    rbac.authorization.k8s.io/unit: "services-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - create
  - delete
  - get
  - patch
  - update
