apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
components:
- ../components/custom-tools

namespace: default

images:
- name: "quay.io/argoproj/argocd"
  newTag: "v2.0.3"
