apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "prometheus-operator"
