apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels:
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/name: "prometheus-operator"
    app.kubernetes.io/version: "v0.44.1"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/name: "prometheus-operator"
