apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
# components:
# - ../../../../components/init-workloads

namespace: default

images:
- name: "argoproj/argocli"
  newTag: "v3.0.7"
- name: "argoproj/workflow-controller"
  newTag: "v3.0.7"
