apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set:admin
  labels:
    rbac.authorization.k8s.io/set: "admin"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules: []
