apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set:cluster-admin
  labels:
    rbac.authorization.k8s.io/set: "cluster-admin"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
