apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set:edit
  labels:
    rbac.authorization.k8s.io/set: "edit"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules: []
