apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: set:view
  labels:
    rbac.authorization.k8s.io/set: "view"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: []
