apiVersion: v1
kind: Service
metadata:
  name: http-https-echo
  labels:
    app.kubernetes.io/name: "http-https-echo"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: "http-https-echo"
