apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/name: "kube-state-metrics"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https
  - name: https-telemetry
    port: 9443
    targetPort: https-telemetry
  selector:
    app.kubernetes.io/name: "kube-state-metrics"
