apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: "sealed-secrets-controller"
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: "sealed-secrets-controller"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: "sealed-secrets-controller"
    spec:
      serviceAccountName: sealed-secrets-controller
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 30
      containers:
      - name: sealed-secrets-controller
        image: docker.io/bitnami/sealed-secrets-controller:v0.17.5
        imagePullPolicy: Always
        command:
        - controller
        args: []
        env: []
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        stdin: false
        tty: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
