apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: kube-system
labels:
- pairs:
    app.kubernetes.io/part-of: "sealed-secrets"
    app.kubernetes.io/version: "v0.17.5"
  includeSelectors: false

images:
- name: "docker.io/bitnami/sealed-secrets-controller"
  newTag: "v0.17.5"
