apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- redis-deployment.yaml
- redis-service.yaml

configMapGenerator:
- name: op-scim-config
  envs:
  - config.env

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "op-scim-bridge"

images:
- name: "1password/scim"
  newTag: "v2.0.0"
