apiVersion: v1
kind: Service
metadata:
  name: op-scim-redis
  labels:
    app.kubernetes.io/name: "op-scim-redis"
spec:
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: "op-scim-redis"
