apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-scim-redis
  labels:
    app.kubernetes.io/name: "op-scim-redis"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "op-scim-redis"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "op-scim-redis"
    spec:
      containers:
      - name: op-scim-redis
        image: redis:latest
        ports:
        - containerPort: 6379
