apiVersion: v1
kind: Service
metadata:
  name: op-scim-bridge
  labels:
    app.kubernetes.io/name: "op-scim-bridge"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3002
  selector:
    app.kubernetes.io/name: "op-scim-bridge"
