apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "grafana"
    app.kubernetes.io/version: "9.0.2"
  includeSelectors: false

images:
- name: "grafana/grafana"
  newTag: "9.0.2"
