apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml

namespace: default

images:
- name: "quay.io/jetstack/cert-manager-cainjector"
  newTag: "v1.0.2"
- name: "quay.io/jetstack/cert-manager-controller"
  newTag: "v1.0.2"
- name: "quay.io/jetstack/cert-manager-webhook"
  newTag: "v1.0.2"
