apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "doraemon"
    app.kubernetes.io/version: "latest"
  includeTemplates: true

images:
- name: "tedilabs/doraemon"
  newTag: "latest"
