apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- crds
- rbac

patchesStrategicMerge:
- deployment.argocd-server.yaml

images:
- name: ghcr.io/argoproj-labs/argocd-extensions
  newTag: v0.2.1
