apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemonset.yaml
- service.yaml
- rbac.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "node-exporter"
    app.kubernetes.io/version: "1.3.1"
  includeTemplates: true

images:
- name: "quay.io/prometheus/node-exporter"
  newTag: "v1.3.1"
