apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  labels:
    app.kubernetes.io/name: "elasticsearch-exporter"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "elasticsearch-exporter"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "elasticsearch-exporter"
    spec:
      containers:
      - name: elasticsearch-exporter
        image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.2.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9108
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 1
          timeoutSeconds: 5
          periodSeconds: 5
