apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-node-termination-handler
spec:
  template:
    spec:
      containers:
      - name: aws-node-termination-handler
        envFrom:
        - configMapRef:
            name: aws-node-termination-handler-config
        ports:
        - name: metrics
          protocol: TCP
          containerPort: 9092
