apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apiservice.yaml
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: kube-system
labels:
- pairs:
    app.kubernetes.io/part-of: "metrics-server"
    app.kubernetes.io/version: "v0.6.2"
  includeTemplates: true

images:
- name: "k8s.gcr.io/metrics-server/metrics-server"
  newTag: "v0.6.2"
