apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml
- service.yaml
# - argo-rollouts-notification-secret.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: "argo-rollouts"
    app.kubernetes.io/version: "v1.3.1"
  includeSelectors: false

images:
- name: quay.io/argoproj/argo-rollouts
  newTag: v1.3.1
