apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  labels:
    app.kubernetes.io/name: "sealed-secrets-controller"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "sealed-secrets-controller"
