apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: "grafana"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "grafana"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "grafana"
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.6.2
        resources: {}
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances pods run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          # requests:
          #   cpu: 100m
          #   memory: 256Mi
          # limits:
          #   cpu: 200m
          #   memory: 512Mi
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: data
      volumes:
      - name: data
        emptyDir: {}
