apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  labels:
    app.kubernetes.io/name: "argocd-notifications-controller"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: "argocd-notifications-controller"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "argocd-notifications-controller"
    spec:
      serviceAccountName: argocd-notifications-controller
      securityContext:
        runAsNonRoot: true
      containers:
      - name: argocd-notifications-controller
        image: argoprojlabs/argocd-notifications:v1.1.1
        imagePullPolicy: Always
        command:
        - /app/argocd-notifications-backend
        - controller
        volumeMounts:
        - mountPath: /app/config/tls
          name: tls-certs
        workingDir: /app
      volumes:
      - name: tls-certs
        configMap:
          name: argocd-tls-certs-cm
