apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml
- configmap.yaml
- secret.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "argo-cd-notification-controller"

images:
- name: "argoprojlabs/argocd-notifications"
  newTag: "v1.1.1"
