apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics
  labels:
    app.kubernetes.io/name: "argocd-notifications-controller-metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9001
    targetPort: 9001
  selector:
    app.kubernetes.io/name: "argocd-notifications-controller"
