apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml
- psp.yaml
patchesStrategicMerge:
- patch.deployment.yaml

configMapGenerator:
- name: aws-node-termination-handler-config
  envs:
  - env

namespace: kube-system
labels:
- pairs:
    app.kubernetes.io/part-of: "aws-node-termination-handler"
    app.kubernetes.io/version: "v1.8.2"
  includeTemplates: true

images:
- name: "public.ecr.aws/aws-ec2/aws-node-termination-handler"
  newTag: "v1.18.2"
