apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: "kafka-exporter"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "kafka-exporter"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "kafka-exporter"
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:v1.4.2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9308
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 1
          timeoutSeconds: 5
          periodSeconds: 5
