apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "kafka-exporter"

images:
- name: "danielqsj/kafka-exporter"
  newTag: "v1.4.2"
