apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "grafana"

images:
- name: "grafana/grafana"
  newTag: "8.2.2"
