apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "api-docs-server"

images:
- name: "api-docs-server"
  newTag: "latest"
