apiVersion: v1
kind: Service
metadata:
  name: api-docs-server
  labels:
    app.kubernetes.io/name: "api-docs-server"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: "api-docs-server"
