apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: apm-server-config
  files:
  - apm-server.yml=files/apm-server.yml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "apm-server"

images:
- name: "docker.elastic.co/apm/apm-server"
  newTag: "7.15.1"
