apiVersion: v1
kind: ServiceAccount
metadata:
  name: apm-server
  labels:
    app.kubernetes.io/name: "apm-server"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apm-server
  labels:
    app.kubernetes.io/name: "apm-server"
rules:
# "" indicates the core API group
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apm-server
  labels:
    app.kubernetes.io/name: "apm-server"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apm-server
subjects:
- kind: ServiceAccount
  name: apm-server
