apiVersion: apps/v1
kind: Deployment
metadata:
  name: redoc
  labels:
    app.kubernetes.io/name: "redoc"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "redoc"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "redoc"
    spec:
      containers:
      - name: redoc
        image: redocly/redoc:latest
        imagePullPolicy: Always
        resources: {}
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances pods run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          # requests:
          #   cpu: 100m
          #   memory: 128Mi
        envFrom:
        - configMapRef:
            name: redoc-config
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
