apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- base
- dashboard

labels:
- pairs:
    app.kubernetes.io/part-of: "argo-rollouts"
    app.kubernetes.io/version: "v1.3.1"
  includeSelectors: false
