apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- cert.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- mutating-webhook-configuration.yaml

namespace: default

images:
- name: "amazon/aws-alb-ingress-controller"
  newTag: "v2.1.3"
