apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apiservice.yaml
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: default

images:
- name: "k8s.gcr.io/metrics-server/metrics-server"
  newTag: "v0.4.2"
