apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:argo-workflowtemplates:view
  labels:
    rbac.authorization.k8s.io/unit: "addons-argo-workflowtemplates-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
## Cluster Scoped
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  verbs:
  - get
  - list
  - watch
## Namspace Scoped
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
  - list
  - watch
