apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:argo-workflows:view
  labels:
    rbac.authorization.k8s.io/unit: "addons-argo-workflows-view"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - cronworkflows
  verbs:
  - get
  - list
  - watch
