apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:argo-workflowtemplates:admin
  labels:
    rbac.authorization.k8s.io/unit: "addons-argo-workflowtemplates-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
## Cluster Scoped
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
## Namspace Scoped
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
