apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:externalsecrets:admin
  labels:
    rbac.authorization.k8s.io/unit: "addons-externalsecrets-admin"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - kubernetes-client.io
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes-client.io
  resources:
  - externalsecrets/status
  verbs:
  - get
  - patch
  - watch
