apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:externalsecrets:view
  labels:
    rbac.authorization.k8s.io/unit: "addons-externalsecrets-view"
rules:
- apiGroups:
  - kubernetes-client.io
  resources:
  - externalsecrets
  verbs:
  - get
  - list
  - watch
