apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit:addons:sealedsecrets:view
  labels:
    rbac.authorization.k8s.io/unit: "addons-secrets-view"
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - get
  - list
  - watch
