apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/
- snapshot-controller/

namespace: kube-system
labels:
- pairs:
    app.kubernetes.io/part-of: "csi-snapshotter"
    app.kubernetes.io/version: "v6.3.1"
  includeTemplates: true

images:
- name: "registry.k8s.io/sig-storage/snapshot-controller"
  newTag: "v6.3.1"
