apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  labels:
    app.kubernetes.io/name: "kafdrop"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "kafdrop"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "kafdrop"
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:latest
        imagePullPolicy: Always
        resources: {}
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances pods run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          # requests:
          #   cpu: 100m
          #   memory: 128Mi
        envFrom:
        - configMapRef:
            name: kafdrop-config
        ports:
        - name: http
          protocol: TCP
          containerPort: 9000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
