apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: kafdrop-config
  envs:
  - config.env

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "kafdrop"

images:
- name: "obsidiandynamics/kafdrop"
  newTag: "3.27.0"
