apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- daemonset.yaml
- service.yaml
- rbac.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "node-exporter"

images:
- name: "quay.io/prometheus/node-exporter"
  newTag: "v1.1.2"
