apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: "node-exporter"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    protocol: TCP
    port: 9100
    targetPort: https
  selector:
    app.kubernetes.io/name: "node-exporter"
