apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
# components:
# - ../../../../components/init-workloads

namespace: default

images:
- name: "docker.io/argoproj/argocli"
  newTag: "v3.1.1"
- name: "docker.io/argoproj/workflow-controller"
  newTag: "v3.1.1"
- name: "docker.io/argoproj/argoexec"
  newTag: "v3.1.1"
