apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    app.kubernetes.io/name: "apm-server"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    app.kubernetes.io/name: "apm-server"
