apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
        - |
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.0.5/kustomize_v4.0.5_linux_amd64.tar.gz -q -O - |tar -xz;
          mv kustomize /custom-tools/kustomize_4.0.5;
          chmod uog+x /custom-tools/kustomize_4.0.5;
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz -q -O - |tar -xz;
          mv kustomize /custom-tools/kustomize_4.2.0;
          chmod uog+x /custom-tools/kustomize_4.2.0;
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz -q -O - |tar -xz;
          mv kustomize /custom-tools/kustomize_4.4.0;
          chmod uog+x /custom-tools/kustomize_4.4.0;
          wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz -q -O - |tar -xz;
          mv kustomize /custom-tools/kustomize_4.5.7;
          chmod uog+x /custom-tools/kustomize_4.5.7;
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/kustomize_4.0.5
          name: custom-tools
          subPath: kustomize_4.0.5
        - mountPath: /usr/local/bin/kustomize_4.2.0
          name: custom-tools
          subPath: kustomize_4.2.0
        - mountPath: /usr/local/bin/kustomize_4.4.0
          name: custom-tools
          subPath: kustomize_4.4.0
        - mountPath: /usr/local/bin/kustomize_4.5.7
          name: custom-tools
          subPath: kustomize_4.5.7
      volumes:
      - name: custom-tools
        emptyDir: {}
