apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        args:
          - |
            wget https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.3/kustomize_2.0.3_linux_amd64 -q -O /custom-tools/kustomize_2.0.3;
            chmod uog+x /custom-tools/kustomize_2.0.3;
            wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.0.5/kustomize_v4.0.5_linux_amd64.tar.gz -q -O - |tar -xz;
            mv kustomize /custom-tools/kustomize_4.0.5;
            chmod uog+x /custom-tools/kustomize_4.0.5;
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - mountPath: /usr/local/bin/kustomize_2.0.3
          name: custom-tools
          subPath: kustomize_2.0.3
        - mountPath: /usr/local/bin/kustomize_4.0.5
          name: custom-tools
          subPath: kustomize_4.0.5
      volumes:
      - name: custom-tools
        emptyDir: {}
