apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
components:
- ../components/custom-tools

namespace: default

images:
- name: "argoproj/argocd"
  newTag: "v1.8.6"
