apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml

namespace: kube-system
commonLabels:
  app.kubernetes.io/part-of: "reflector"

images:
- name: "emberstack/kubernetes-reflector"
  newTag: "6.1.23"
