apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml

namespace: kube-system
labels:
- pairs:
    app.kubernetes.io/part-of: "reflector"
    app.kubernetes.io/version: "6.1.23"
  includeSelectors: false

images:
- name: "emberstack/kubernetes-reflector"
  newTag: "6.1.23"
