apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["watch", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector
roleRef:
  kind: ClusterRole
  name: reflector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: reflector
  # namespace: kube-system
