apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reflector
    spec:
      serviceAccountName: reflector
      securityContext:
        fsGroup: 2000
      containers:
      - name: reflector
        image: "emberstack/kubernetes-reflector:6.0.21"
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_Serilog__MinimumLevel__Default
          value: "Information"
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        ports:
        - name: http
          containerPort: 25080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
