apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: atlantis-config
  envs:
  - config.env

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "atlantis"

images:
- name: "ghcr.io/runatlantis/atlantis"
  newTag: "v0.17.6"
