apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-node-termination-handler
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
  sampleLimit: 5000
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-node-termination-handler
