apiVersion: v1
kind: Service
metadata:
  name: aws-node-termination-handler
  labels:
    app.kubernetes.io/name: aws-node-termination-handler
    app.kubernetes.io/instance: aws-node-termination-handler
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 9092
    targetPort: metrics
  selector:
    app.kubernetes.io/name: aws-node-termination-handler
