apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

configMapGenerator:
- name: kibana-config
  files:
  - kibana.yml=files/kibana.yml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "kibana"

images:
- name: "docker.elastic.co/kibana/kibana"
  newTag: "7.13.2"
