apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
components:
- ../components/custom-tools

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "argocd"
    app.kubernetes.io/version: "v2.4.2"
  includeSelectors: false

images:
- name: "quay.io/argoproj/argocd"
  newTag: "v2.4.2"
