apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  labels:
    app.kubernetes.io/name: "heartbeat"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heartbeat
  labels:
    app.kubernetes.io/name: "heartbeat"
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - pods
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heartbeat
  labels:
    app.kubernetes.io/name: "heartbeat"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heartbeat
subjects:
- kind: ServiceAccount
  name: heartbeat
  # namespace:
