apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
  labels:
    k8s-app: "aws-node"
spec:
  group: crd.k8s.amazonaws.com
  scope: Cluster
  preserveUnknownFields: false
  names:
    kind: ENIConfig
    plural: eniconfigs
    singular: eniconfig
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
