apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- poddisruptionbudget.yaml
- rbac.yaml
- service.yaml

configMapGenerator:
- name: logstash-config
  files:
  - logstash.yml=files/logstash.yml
  - pipelines.yml=files/pipelines.yml
- name: logstash-pipelines
  files:
  - main.conf=files/pipelines/main.conf
- name: logstash-patterns
  files: []
- name: logstash-files
  files: []

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "logstash"

images:
- name: "docker.elastic.co/logstash/logstash"
  newTag: "7.15.1"
