apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds.yaml
- configmaps.yaml
- deployment.cert-manager.yaml
- deployment.cert-manager-webhook.yaml
- deployment.cert-manager-cainjector.yaml
- services.yaml
- rbac.yaml
- admission.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/1
      value: --leader-election-namespace=$(POD_NAMESPACE)
  target:
    version: v1
    kind: Deployment
    name: cert-manager-cainjector
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/2
      value: --leader-election-namespace=$(POD_NAMESPACE)
  target:
    version: v1
    kind: Deployment
    name: cert-manager


configurations:
- configurations.yaml
namespace: cert-manager

images:
- name: "quay.io/jetstack/cert-manager-cainjector"
  newTag: "v1.10.1"
- name: "quay.io/jetstack/cert-manager-controller"
  newTag: "v1.10.1"
- name: "quay.io/jetstack/cert-manager-webhook"
  newTag: "v1.10.1"
