apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- rbac.yaml

configMapGenerator:
- name: botkube-config
  files:
  - resource_config.yaml=files/resource_config.yaml
  - comm_config.yaml=files/comm_config.yaml

namespace: default
commonLabels:
  app.kubernetes.io/part-of: "botkube"

images:
- name: "ghcr.io/infracloudio/botkube"
  newTag: "v0.12.2"
