apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- configmap.yaml
- deployment.yaml
- deployment.cert-manager-webhook.yaml
- deployment.cert-manager-cainjector.yaml
- service.yaml
- service.cert-manager-webhook.yaml
- rbac.yaml
- admission.yaml

# namespace: cert-manager

images:
- name: "quay.io/jetstack/cert-manager-cainjector"
  newTag: "v1.7.1"
- name: "quay.io/jetstack/cert-manager-controller"
  newTag: "v1.7.1"
- name: "quay.io/jetstack/cert-manager-webhook"
  newTag: "v1.7.1"
