apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- rbac.yaml
- service.yaml

namespace: default

images:
- name: "docker.io/bitnami/sealed-secrets-controller"
  newTag: "v0.15.0"
