apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml

namespace: default
labels:
- pairs:
    app.kubernetes.io/part-of: "rollouts-demo"
  includeSelectors: false
